--MySQL DATABASE

DROP DATABASE IF EXISTS motorraeder;
CREATE DATABASE motorraeder;
USE motorraeder;

--DROP TABLE raeder CASCADE;
CREATE TABLE raeder (
	id INTEGER,
	marke VARCHAR(255),
	modell VARCHAR(255),
	leistung BIGINT,
	date BIGINT,
	PRIMARY KEY (id)
)ENGINE=INNODB;

CREATE TABLE deletedEntry (
	id INTEGER,
	marke VARCHAR(255),
	modell VARCHAR(255),
	leistung BIGINT,
	date BIGINT,
	PRIMARY KEY (id)
)ENGINE=INNODB;


INSERT INTO raeder VALUES (1, 'Honda', 'CBR-600',120, UNIX_TIMESTAMP());
INSERT INTO raeder VALUES (2, 'Honda', 'CBR-1000',180, UNIX_TIMESTAMP());
INSERT INTO raeder VALUES (3, 'Yamaha', 'R6',130, UNIX_TIMESTAMP());
INSERT INTO raeder VALUES (4, 'Yamaha', 'R1',190, UNIX_TIMESTAMP());
INSERT INTO raeder VALUES (5, 'Kawasaki', 'ZX-10R',200, UNIX_TIMESTAMP());
INSERT INTO raeder VALUES (6, 'BMW', 'S1000RR',200, UNIX_TIMESTAMP());
INSERT INTO raeder VALUES (7, 'Suzuki', 'GSR 600',101, UNIX_TIMESTAMP());





DELIMITER $$
CREATE TRIGGER updateTimestamp BEFORE UPDATE ON raeder
FOR EACH ROW
BEGIN
	SET NEW.date = UNIX_TIMESTAMP();
END;
$$ DELIMITER;

DELIMITER $$

CREATE TRIGGER deletedEntry BEFORE DELETE ON raeder
FOR EACH ROW
BEGIN
	INSERT INTO deletedEntry SELECT * FROM raeder WHERE id= old.id;
END;
$$ DELIMITER;

UPDATE raeder SET marke='AVG' WHERE marke='Ford';